framework:
    assets:
        packages:
            bootstrapTheme:
                json_manifest_path: '%kernel.project_dir%/public/bootstrap-theme/manifest.json'
            admin:
                json_manifest_path: '%kernel.project_dir%/public/build/admin/manifest.json'
            shop:
                json_manifest_path: '%kernel.project_dir%/public/build/shop/manifest.json'
            app.admin:
                json_manifest_path: '%kernel.project_dir%/public/build/app/admin/manifest.json'
            app.shop:
                json_manifest_path: '%kernel.project_dir%/public/build/app/shop/manifest.json'
            wishlist_shop:
                json_manifest_path: '%kernel.project_dir%/public/build/bitbag/wishlist/shop/manifest.json'
            wishlist_admin:
                json_manifest_path: '%kernel.project_dir%/public/build/bitbag/wishlist/admin/manifest.json'
