# config/packages/sylius_resource.yaml
sylius_resource:
    resources:
        app.faq:
            driver: doctrine/orm # You can use also different driver here
            classes:
                model: App\Entity\Faq\Faq
                form: App\Form\Type\Faq\FaqType
                repository: App\Repository\Faq\FaqRepository
            translation:
                classes:
                    model: App\Entity\Faq\FaqTranslation
                    form: App\Form\Type\Faq\FaqTranslationType
        app.banner_image:
            driver: doctrine/orm
            classes:
                model: App\Entity\BannerImage\BannerImage
                form: App\Form\Type\BannerImage\BannerImageType
                repository: App\Repository\BannerImage\BannerImageRepository
        app.product_bundle:
            driver: doctrine/orm
            classes:
                model: App\Entity\ProductBundle\ProductBundle
                repository: App\Repository\ProductBundle\ProductBundleRepository