sylius_ui:
    events:
        sylius.shop.homepage:
            blocks:
                bundle:
                    template: "page/Homepage/ProductBundle/_index.html.twig"
                    priority: 50
        sylius.shop.product.show.content:
            blocks:
                bundle:
                    template: "page/Product/Show/ProductBundle/_index.html.twig"
                    priority: 20