webpack_encore:
    output_path: '%kernel.project_dir%/public/build/default'
    builds:
        bootstrapTheme: '%kernel.project_dir%/public/bootstrap-theme'
        admin: '%kernel.project_dir%/public/build/admin'
        shop: '%kernel.project_dir%/public/build/shop'
        app.admin: '%kernel.project_dir%/public/build/app/admin'
        app.shop: '%kernel.project_dir%/public/build/app/shop'
        wishlist_shop: '%kernel.project_dir%/public/build/bitbag/wishlist/shop'
        wishlist_admin: '%kernel.project_dir%/public/build/bitbag/wishlist/admin'
