sylius_paypal_webhook:
    resource: "@SyliusPayPalPlugin/Resources/config/webhook_routing.yaml"

app_page_about:
    path: /{_locale}/page/about
    methods: [GET]
    controller: App\Controller\AboutController::index
    requirements:
        _locale: ^[A-Za-z]{2,4}(_([A-Za-z]{4}|[0-9]{3}))?(_([A-Za-z]{2}|[0-9]{3}))?$

app_page_search:
    path: /{_locale}/page/search
    methods: [GET]
    controller: App\Controller\SearchController::index
    requirements:
        _locale: ^[A-Za-z]{2,4}(_([A-Za-z]{4}|[0-9]{3}))?(_([A-Za-z]{2}|[0-9]{3}))?$

app_page_faq:
    path: /{_locale}/page/faq
    methods: [GET]
    controller: App\Controller\FaqController::index
    requirements:
        _locale: ^[A-Za-z]{2,4}(_([A-Za-z]{4}|[0-9]{3}))?(_([A-Za-z]{2}|[0-9]{3}))?$

app_page_product_bundle:
    path: /bundle
    methods: [GET]
    controller: App\Controller\ProductBundleController::index

app_add_bundle:
    path: /bundle/{name}
    methods: [POST]
    defaults:
        _controller: App\Controller\ProductBundleAction

app_admin_faq:
    resource: |
        alias: app.faq
        section: admin
        templates: "@SyliusAdmin\\Crud"
        redirect: index
        grid: app_admin_faq
        vars:
            all:
                subheader: app.ui.faq
                templates:
                    form: 'Faq/_form.html.twig'
            index:
                icon: 'file image outline'
    type: sylius.resource
    prefix: admin

app_admin_banner_image:
    resource: |
        alias: app.banner_image
        section: admin
        templates: "@SyliusAdmin\\Crud"
        redirect: index
        grid: app_admin_banner_image
        vars:
            all:
                subheader: app.ui.banner_image
                templates:
                    form: 'BannerImage/_form.html.twig'
            index:
                icon: 'file image outline'
    type: sylius.resource
    prefix: /admin

app_product_bundle:
    resource: |
        alias: app.product_bundle
        section: admin
        templates: "@SyliusAdmin\\Crud"
        redirect: index
        grid: app_admin_product_bundle
        vars:
            all:
                subheader: app.ui.product_bundle
            index:
                icon: 'file image outline'
    type: sylius.resource
    prefix: /admin